# Script for Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet --version

- script: dotnet restore ./implementation/PersistentProcess/PersistentProcess.Common/PersistentProcess.Common.csproj --verbosity m
  displayName: 'dotnet restore common'

- script: dotnet restore ./implementation/PersistentProcess/PersistentProcess.Test/PersistentProcess.Test.csproj --verbosity m
  displayName: 'dotnet restore test'

- script: dotnet build ./implementation/PersistentProcess/PersistentProcess.Common/PersistentProcess.Common.csproj
  displayName: 'dotnet build common'

- script: dotnet build ./implementation/PersistentProcess/PersistentProcess.Test/PersistentProcess.Test.csproj
  displayName: 'dotnet build test'

- script: dotnet test ./implementation/PersistentProcess/PersistentProcess.Test/PersistentProcess.Test.csproj --logger trx
  displayName: 'test'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
